# PURL configuration for http://purl.obolibrary.org/obo/ncbitaxon

idspace: NCBITaxon
base_url: /obo/ncbitaxon

products:
- ncbitaxon.owl: https://github.com/obophenotype/ncbitaxon/releases/download/current/ncbitaxon.owl
- ncbitaxon.obo: https://github.com/obophenotype/ncbitaxon/releases/download/current/ncbitaxon.obo

term_browser: ontobee
example_terms:
- NCBITaxon_1

entries:
- prefix: /subsets/
  replacement: https://github.com/obophenotype/ncbitaxon/releases/download/current/
- prefix: /2
  replacement: https://github.com/obophenotype/ncbitaxon/releases/download/v2
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/NCBITaxon_1
    to: http://www.ontobee.org/browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_1
- prefix: /
  replacement: https://github.com/obophenotype/ncbitaxon/releases/download/current/


