# PURL configuration for http://purl.obolibrary.org/obo/omrse

idspace: OMRSE
base_url: /obo/omrse

products:
- omrse.owl: https://raw.githubusercontent.com/ufbmi/OMRSE/master/omrse/omrse.owl

term_browser: ontobee
example_terms:
- OMRSE_00000098

entries:

- exact: /dev/omrse.owl
  replacement: https://raw.githubusercontent.com/ufbmi/OMRSE/devel/omrse/omrse.owl
  
- exact: /dev/omrse-core.owl
  replacement: https://raw.githubusercontent.com/ufbmi/OMRSE/devel/omrse/omrse-core.owl

- exact: /dao.owl
  replacement: https://raw.githubusercontent.com/ufbmi/demo-app-ontology/master/DAO.owl

- exact: /dev/language.owl
  replacement: https://raw.githubusercontent.com/ufbmi/OMRSE/devel/omrse/language/omrse-language.owl

- exact: /language.owl
  replacement: https://raw.githubusercontent.com/ufbmi/OMRSE/master/omrse/language/omrse-language.owl
  
- exact: /language-individuals.owl
  replacement: https://raw.githubusercontent.com/ufbmi/OMRSE/master/omrse/language/language-individuals.owl

- exact: /dev/language-individuals.owl
  replacement: https://raw.githubusercontent.com/ufbmi/OMRSE/devel/omrse/language/language-individuals.owl

- exact: /dev/education.owl
  replacement: https://raw.githubusercontent.com/ufbmi/OMRSE/devel/omrse/education/omrse-education.owl
