# PURL configuration for http://purl.obolibrary.org/obo/uo

idspace: UO
base_url: /obo/uo

products:
- uo.owl: https://raw.githubusercontent.com/bio-ontology-research-group/unit-ontology/master/uo.owl
- uo.obo: https://raw.githubusercontent.com/bio-ontology-research-group/unit-ontology/master/unit.obo

term_browser: ontobee
example_terms:
- UO_0000000
